import numpy as np

APP_WIDTH = 1900
PLAYLIST_WIDTH = 300

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 1200
BOTTOM_BORDER_HEIGHT = 70
VISUALISATION_HEIGHT = WINDOW_HEIGHT // 5
NUM_VISUALISATIONS = 3  # number of layers of visualisations above the spectrogram
SPECTROGRAM_HEIGHT = WINDOW_HEIGHT - BOTTOM_BORDER_HEIGHT - VISUALISATION_HEIGHT * NUM_VISUALISATIONS
FREQUENCY_LABEL_WIDTH = 90
VISUALISATION_HALF_WIDTH = (WINDOW_WIDTH - FREQUENCY_LABEL_WIDTH) // 2
VISUALISATION_THIRD_WIDTH = WINDOW_WIDTH // 3
RIGHT_CHANNEL_VISUALISATION_START = (WINDOW_WIDTH + FREQUENCY_LABEL_WIDTH) // 2

SAMPLE_RATE = 44100
WINDOW_SIZE = 8192
BUFFER_SIZE = WINDOW_SIZE
HOP_SIZE = 500  # 200 for SAMPLE RATE = 22050
SPECTROGRAM_MAX_FREQUENCY = 16000   # 16kHz is good for most 128kbps mp3 files
if SPECTROGRAM_MAX_FREQUENCY > SAMPLE_RATE // 2:
    SPECTROGRAM_MAX_FREQUENCY = SAMPLE_RATE // 2

FONT_SCALE = 2
FONT_SIZE = 12
INIT_FILE = r"<put a valid file path here if you want a track in the playlist on load>"

# EQ bands (centre frequencies in Hz)
EQ_BANDS = np.geomspace(20, SAMPLE_RATE // 2, 30).round().astype(int).tolist()  # or 40
NUM_PHASE_SCOPE_POINTS = 512

HANNING = np.hanning(WINDOW_SIZE)
